/**
 * Home / base countries for catalog airlines and airports.
 * Used by country-name search ("Inglaterra", "Portugal", "France", …).
 */
export const CATALOG_HOME_COUNTRIES: Record<string, string[]> = {
  // Airlines
  ryanair: ["IE"],
  easyjet: ["GB"],
  "british-airways": ["GB"],
  "wizz-air": ["HU"],
  tap: ["PT"],
  lufthansa: ["DE"],
  eurowings: ["DE"],
  "air-france": ["FR"],
  "transavia-france": ["FR"],
  klm: ["NL"],
  transavia: ["NL"],
  iberia: ["ES"],
  "iberia-express": ["ES"],
  vueling: ["ES"],
  "air-europa": ["ES"],
  "ita-airways": ["IT"],
  "brussels-airlines": ["BE"],
  "aer-lingus": ["IE"],
  jet2: ["GB"],
  "eastern-airways": ["GB"],
  "tui-airways": ["GB"],
  "virgin-atlantic": ["GB"],
  sas: ["SE", "DK", "NO"],
  norwegian: ["NO"],
  finnair: ["FI"],
  swiss: ["CH"],
  austrian: ["AT"],
  lot: ["PL"],
  aegean: ["GR"],
  condor: ["DE"],
  volotea: ["ES"],
  "croatia-airlines": ["HR"],
  tarom: ["RO"],
  luxair: ["LU"],
  icelandair: ["IS"],
  "air-baltic": ["LV"],
  smartwings: ["CZ"],
  sunexpress: ["TR", "DE"],

  // Airports
  heathrow: ["GB"],
  gatwick: ["GB"],
  manchester: ["GB"],
  lisbon: ["PT"],
  stansted: ["GB"],
  luton: ["GB"],
  birmingham: ["GB"],
  edinburgh: ["GB"],
  glasgow: ["GB"],
  bristol: ["GB"],
  porto: ["PT"],
  faro: ["PT"],
  madrid: ["ES"],
  barcelona: ["ES"],
  malaga: ["ES"],
  palma: ["ES"],
  "paris-cdg": ["FR"],
  "paris-orly": ["FR"],
  nice: ["FR"],
  lyon: ["FR"],
  frankfurt: ["DE"],
  munich: ["DE"],
  berlin: ["DE"],
  dusseldorf: ["DE"],
  hamburg: ["DE"],
  "rome-fiumicino": ["IT"],
  "milan-malpensa": ["IT"],
  "milan-linate": ["IT"],
  venice: ["IT"],
  amsterdam: ["NL"],
  brussels: ["BE"],
  dublin: ["IE"],
  warsaw: ["PL"],
  krakow: ["PL"],
  athens: ["GR"],
  vienna: ["AT"],
  zurich: ["CH"],
  geneva: ["CH"],
  copenhagen: ["DK"],
  oslo: ["NO"],
  stockholm: ["SE"],
  helsinki: ["FI"],
  prague: ["CZ"],
  budapest: ["HU"],
  bucharest: ["RO"],
};

export function getCatalogHomeCountries(itemId: string): string[] {
  return CATALOG_HOME_COUNTRIES[itemId] ?? [];
}
